### ISSUE TITLE
updateObjBrowser() error

### ISSUE THREAD

**Issue by Nidish96** [psicofil/SalomeToCalculix#4]
Thank you for this! Hoping this gets absorbed into Salome soon!

I tried this in the 2019.0.3 version of Salome_meca (https://www.code-aster.org/spip.php?article303) and I have the following error:
`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<string>", line 209, in <module>
TypeError: updateObjBrowser() takes 1 positional argument but 2 were given`

I used the unv2ccx binary from the command line and that works good.

**Comment by imirzov** [comment]
Thanks! Confirm the same error for Salome 9.3.0.

**Comment by imirzov** [comment]
Please, try it:
https://github.com/calculix/salome2ccx/releases/tag/Salome.9.3.0
